name: Deploy MkDocs Material to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is not main

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Deploy MkDocs to GitHub Pages
        run: |
          mkdocs gh-deploy --remote-branch gh-pages --force
